### ISSUE TITLE
Configuring IO

### ISSUE THREAD

**Issue by kpp** [dsouzadyn/cerebrallib#1]
How about `.stdin(Stdio::piped())` and `.stdout(Stdio::piped())` like in https://doc.rust-lang.org/std/process/index.html?

**Comment by dsouzadyn** [comment]
Sorry, I didn't quite get you, I'm kind of new to rust. Can you elaborate?

**Comment by kpp** [comment]
So right now you take global stdin and output to stdout. One may want to capture the output and send it to somewhere other than stdout. Like in https://github.com/squiidz/brain-rs/blob/master/src/lib.rs#L19

**Comment by dsouzadyn** [comment]
Oh, never thought of that, I'll see what I can do, thanks :smiley:
